# Generated by Django 6.0.5 on 2026-06-06 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_class_timing_date'),
        ('liveclasses', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='lesson_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_live_class', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_status',
            field=models.CharField(choices=[('none', 'Not Recorded'), ('recording', 'Recording in Progress'), ('processing', 'Processing'), ('ready', 'Ready'), ('added', 'Added to Course')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
    ]
