# Generated by Django 5.2.13 on 2026-05-13 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('delivery_method', models.CharField(choices=[('digital', 'Digital Download'), ('post', 'Postal Mail'), ('pdf', 'PDF Download')], default='digital', max_length=10)),
                ('postal_address', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('exam_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='exams.examattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('description', models.TextField(blank=True)),
                ('job_link', models.URLField()),
                ('min_score_required', models.PositiveIntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='partner_companies', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Partner Companies',
            },
        ),
    ]
